apiVersion: v1
kind: Service
metadata:
  name: chat-server-mysql
  labels:
    app: server
  namespace: hau-mysql 
spec:
  ports:
    - port: 3306
  selector:
    app: server
    tier: chat-server-mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-server-mysql
  labels:
    app: server
    tier: chat-server-mysql
  namespace: hau-mysql 
spec:
  
  selector:
    matchLabels:
      app: server
      tier: chat-server-mysql
  template:
    metadata:
      labels:
        app: server
        tier: chat-server-mysql
    spec:
      containers:
      - image: 10.105.68.53:5000/mysql:hau
        name: chat-server-mysql
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      imagePullSecrets:
        - name: intern-registry
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
