apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-storage-mysql-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage-mysql
  resources:
    requests:
      storage: 2Gi
