apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-test
  labels:
    app: server-test
  namespace: soldiers-ext 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-test
  template:
    metadata:
      labels:
        app: server-test
    spec:
      containers:
        - name: server
          image: 10.105.68.53:5000/server:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
            - name: MYSQL_CONT_NAME
              value: "chat-server-mysql"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: intern-registry
---
apiVersion: v1
kind: Service
metadata:
  name: server-test
  labels:
    app: server-test
  namespace: soldiers-ext 
spec:
  type: NodePort
  selector:
    app: server-test
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31111
